name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main   # 👈 change to "master" if your default branch is master
  workflow_dispatch:  # allows manual runs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci   # or "npm install" if you don’t use package-lock.json

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages     # 👈 branch GitHub Pages serves from
          folder: dist         # 👈 Vite build output folder
